import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PredictionData {
  confidence: number;
  affectedAreaPercentage: number;
  predictedClass: string;
  originalImage?: string;
  gradcamImage?: string;
  overlayImage?: string;
}

export async function generatePneumoniaReport(data: PredictionData): Promise<void> {
  try {
    // Create a new PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;
    const contentWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Set colors
    const headerColor: [number, number, number] = [25, 118, 210]; // Blue
    const textColor: [number, number, number] = [33, 33, 33]; // Dark gray
    const lightColor: [number, number, number] = [242, 242, 242]; // Light gray

    // Title Section
    pdf.setFillColor(...headerColor);
    pdf.rect(0, yPosition, pageWidth, 30, 'F');
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Pneumonia Detection Report', margin, yPosition + 12);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition + 22);

    yPosition += 35;

    // Patient Information Section (placeholder for future integration)
    pdf.setTextColor(...textColor);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Analysis Results', margin, yPosition);
    yPosition += 8;

    // Results Box
    pdf.setFillColor(...lightColor);
    pdf.rect(margin, yPosition, contentWidth, 50, 'F');
    pdf.setLineWidth(0.5);
    pdf.setDrawColor(200, 200, 200);
    pdf.rect(margin, yPosition, contentWidth, 50);

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(...textColor);

    let resultY = yPosition + 8;
    pdf.text('Prediction:', margin + 5, resultY);
    pdf.setFont('helvetica', 'normal');
    const predictionText = data.predictedClass === 'pneumonia' ? 'Pneumonia Detected' : 'Normal (No Pneumonia)';
    const predictionColor: [number, number, number] = data.predictedClass === 'pneumonia' ? [211, 47, 47] : [56, 142, 60]; // Red or Green
    pdf.setTextColor(...predictionColor);
    pdf.text(predictionText, margin + 50, resultY);

    resultY += 8;
    pdf.setTextColor(...textColor);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Confidence Score:', margin + 5, resultY);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${(data.confidence * 100).toFixed(2)}%`, margin + 50, resultY);

    resultY += 8;
    pdf.setFont('helvetica', 'bold');
    pdf.text('Affected Area:', margin + 5, resultY);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`${data.affectedAreaPercentage.toFixed(2)}%`, margin + 50, resultY);

    resultY += 8;
    pdf.setFont('helvetica', 'bold');
    pdf.text('Analysis Date:', margin + 5, resultY);
    pdf.setFont('helvetica', 'normal');
    pdf.text(new Date().toLocaleDateString(), margin + 50, resultY);

    yPosition += 60;

    // Medical Disclaimer Section
    pdf.setTextColor(...textColor);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Important Medical Disclaimer', margin, yPosition);
    yPosition += 7;

    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const disclaimerText = 
      'This report is generated by an artificial intelligence system for educational and informational purposes only. ' +
      'This analysis MUST NOT be used as a substitute for professional medical diagnosis and treatment. ' +
      'All interpretations should be reviewed and validated by a qualified healthcare professional. ' +
      'In case of medical concerns, please consult with a physician immediately.';

    const disclaimerLines = pdf.splitTextToSize(disclaimerText, contentWidth - 10);
    pdf.setTextColor(211, 47, 47); // Red color for disclaimer
    pdf.text(disclaimerLines, margin + 5, yPosition);
    yPosition += disclaimerLines.length * 5 + 5;

    // X-ray Images Section
    yPosition += 5;
    pdf.setTextColor(...textColor);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('X-ray Analysis Images', margin, yPosition);
    yPosition += 10;

    const imageWidth = (contentWidth - 10) / 3;
    const imageHeight = (imageWidth * 3) / 4; // Maintain aspect ratio
    let xPosition = margin + 5;

    try {
      // Original Image
      if (data.originalImage) {
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Original X-ray', xPosition, yPosition - 2);
        pdf.addImage(data.originalImage, 'JPEG', xPosition, yPosition, imageWidth, imageHeight);
      }

      // Grad-CAM Image
      xPosition += imageWidth + 5;
      if (data.gradcamImage) {
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Grad-CAM Heatmap', xPosition, yPosition - 2);
        pdf.addImage(data.gradcamImage, 'JPEG', xPosition, yPosition, imageWidth, imageHeight);
      }

      // Overlay Image
      xPosition += imageWidth + 5;
      if (data.overlayImage) {
        pdf.setFontSize(9);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Overlay Visualization', xPosition, yPosition - 2);
        pdf.addImage(data.overlayImage, 'JPEG', xPosition, yPosition, imageWidth, imageHeight);
      }
    } catch (error) {
      console.error('[v0] Error adding images to PDF:', error);
    }

    yPosition += imageHeight + 15;

    // Technical Details Section
    if (yPosition < pageHeight - 40) {
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(...textColor);
      pdf.text('Technical Details', margin, yPosition);
      yPosition += 7;

      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      const technicalText = [
        'Model: DenseNet121 (Pre-trained on ImageNet)',
        'Visualization Method: Gradient-weighted Class Activation Mapping (Grad-CAM)',
        'Image Resolution: 224 x 224 pixels',
        'Analysis Framework: TensorFlow/Keras',
        'Explainability: AI-generated heatmap showing areas of concern'
      ];

      technicalText.forEach((line) => {
        pdf.text(line, margin + 5, yPosition);
        yPosition += 5;
      });
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Page 1 of 1 | Report generated by PneumoVision AI | ${new Date().getFullYear()}`,
      margin,
      pageHeight - 10
    );

    // Download the PDF
    pdf.save(`Pneumonia_Analysis_${new Date().getTime()}.pdf`);
    console.log('[v0] PDF report generated and downloaded successfully');
  } catch (error) {
    console.error('[v0] Error generating PDF report:', error);
    throw new Error('Failed to generate PDF report. Please try again.');
  }
}

export async function captureImageElement(elementId: string): Promise<string> {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error(`Element with ID ${elementId} not found`);
    }
    const canvas = await html2canvas(element, {
      backgroundColor: '#ffffff',
      scale: 2,
    });
    return canvas.toDataURL('image/jpeg', 0.95);
  } catch (error) {
    console.error('[v0] Error capturing image:', error);
    throw new Error('Failed to capture image. Please try again.');
  }
}
